name: Triggers

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'releases/**'
      - 'feature/**'
      - 'fix/**'
    paths:
      - '**.js'
      - '**.py'
  pull_request:
    types: [opened, labeled]
    branches:
      - 'develop'
    paths:
      - '**.js'
      - '**.py'
  issues:
    types: [opened, edited, closed]

jobs:
  run-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Message 1
        run: echo "El servidor ya tiene el código y está listo."

      - name: Message 2 (Usando Contextos)
        run: echo "Este workflow fue detonado por el evento... ${{ github.event_name }}"
